### ISSUE TITLE
Attempting to return a non-serializable object in a remote function kills the worker

### ISSUE THREAD

**Issue by Wapaul1** [amplab/ray#390]
Define a custom class:
```python
class Foo(object):
  def __init__(self):
    self.a = 5
```
Then define a remote function that returns this class:
```python
@ray.remote([],[Foo])
def f():
  return Foo()
```
After starting ray, simply call the function and you will get:
```
File "/home/ubuntu/ray/lib/python/ray/../../../scripts/default_worker.py", line 16, in <module>                                                                                            
    ray.worker.main_loop()
File "/home/ubuntu/ray/lib/python/ray/worker.py", line 1056, in main_loop
    process_task(command_args)
File "/home/ubuntu/ray/lib/python/ray/worker.py", line 979, in process_task
    store_outputs_in_objstore(return_objectids, outputs, worker) # store output in local object store                                                                                             
File "/home/ubuntu/ray/lib/python/ray/worker.py", line 1387, in store_outputs_in_objstore   
    worker.put_object(objectids[i], outputs[i])                                                                                           
File "/home/ubuntu/ray/lib/python/ray/worker.py", line 439, in put_object
    object_capsule, contained_objectids = serialization.serialize(self.handle, value) # contained_objectids is a list of the objectids contained in object_capsule                                                                                                                                                                                      
File "/home/ubuntu/ray/lib/python/ray/serialization.py", line 60, in serialize
  obj_capsule, contained_objectids = raylib.serialize_object(worker_capsule, primitive_obj) # contained_objectids is a list of the objectids contained in obj
<ray.ObjectID at 0x7f6ae00ae490>                                                                                             

ray.error: serialization: type not know

Successfully shut down Ray.
```

which shuts the worker down.

**Comment by robertnishihara** [comment]
This works now. The code

```python
import ray

ray.init(start_ray_local=True, num_workers=1)

class Foo(object):
  def __init__(self):
    self.a = 5

@ray.remote
def f():
  return Foo()

f.remote()
```

now prints the following (and does not kill any processes).

```
Remote function __main__.f failed with:

Traceback (most recent call last):
  File "/Users/rkn/Workspace/ray/lib/python/ray/worker.py", line 347, in put_object
    schema, size, serialized = numbuf_serialize(value)
  File "/Users/rkn/Workspace/ray/lib/python/ray/worker.py", line 41, in numbuf_serialize
    return libnumbuf.serialize_list([value])
  File "/Users/rkn/Workspace/ray/lib/python/ray/serialization.py", line 174, in serialize
    raise Exception("Ray does not know how to serialize the object {}. To fix this, call 'ray.register_class' on the class of the object.".format(obj))
Exception: Ray does not know how to serialize the object <__main__.Foo object at 0x103f78c10>. To fix this, call 'ray.register_class' on the class of the object.
```

Adding `ray.register_class(Foo)` above solves the problem.
